# Generated by Django 4.1.10 on 2023-08-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("title", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        default="teachers/default_teacher_image.jpg",
                        upload_to="teachers/%Y/%m/%d/",
                    ),
                ),
                ("facebook", models.URLField(blank=True, max_length=100)),
                ("twittter", models.URLField(blank=True, max_length=100)),
                ("linkedin", models.URLField(blank=True, max_length=100)),
                ("youtube", models.URLField(blank=True, max_length=100)),
            ],
        ),
    ]
